### ISSUE TITLE
Where is the content of /macOS/AppleLocalization?

### ISSUE THREAD

**Issue by b123400** [kishikawakatsumi/applelocalization-tools#1]
Hello, I wonder how can I access the content of `/macOS/AppleLocalization`. Is it refering to another repository?
Thank you

**Comment by kishikawakatsumi** [comment]
The macOS code does not exist because I forgot to commit it and deleted it. The format of strings has changed in the latest OS, so I plan to rewrite it when I support the latest OS.

**Comment by b123400** [comment]
Ok, thank you very much!
